# Generated by Django 5.1.1 on 2024-09-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
