# Generated by Django 5.1.1 on 2024-09-17 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_remove_user_bio_remove_user_profile_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
    ]
