# Generated by Django 5.1.1 on 2024-09-17 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_profile_post_alter_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
