# Generated by Django 5.1.1 on 2024-09-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0015_post_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='working_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
