# Generated by Django 5.1.1 on 2024-09-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0016_profile_working_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='working_at',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
