# Generated by Django 5.1.1 on 2024-09-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0017_alter_profile_working_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='relations',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
