# Generated by Django 5.1.1 on 2024-10-10 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0022_post_likes_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Likes',
        ),
    ]
