# Generated by Django 5.1.1 on 2024-10-10 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0024_alter_like_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='relations',
        ),
    ]
