# Generated by Django 5.1.1 on 2024-11-14 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0031_alter_comment_post_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Profile.post'),
        ),
    ]
