# Generated by Django 4.2.25 on 2025-10-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0032_post_comment_status_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(blank=True, null=True, verbose_name='کپشن'),
        ),
        migrations.AlterField(
            model_name='post',
            name='comment_status',
            field=models.BooleanField(default=False, verbose_name='فعال سازی کامنت'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to='Post_pics', verbose_name='تصویر'),
        ),
    ]
