# Generated by Django 5.1.1 on 2024-11-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatuser', '0002_alter_chat_user1_alter_chat_user2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_id',
            field=models.SlugField(unique=True),
        ),
    ]
